name: Deploy Noise Generator

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the NoiseGenerator
      run: python your_script_name.py  # نام اسکریپت خود را جایگزین کنید

    - name: Save output
      run: |
        mkdir -p output
        cp noisy_*.xlsx output/  # کپی کردن فایل خروجی به پوشه output
